name: windows
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 10 * * 1"

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: master

    - run: zig build test
  